services:

    thinkawitch.subscription.strategy.end_last_default:
        class: Thinkawitch\SubscriptionBundle\Strategy\Subscription\SubscriptionEndLastStrategy
        arguments:
            - "%thinkawitch_subscription.config.subscription.class%"
            - "%thinkawitch_subscription.config.subscription_interval.class%"
            - "@thinkawitch.subscription.strategy.product.default"
        tags:
            - { name: thinkawitch.subscription.strategy, type: subscription, strategy: end_last_default }


    thinkawitch.subscription.strategy.end_last_exact:
        class: Thinkawitch\SubscriptionBundle\Strategy\Subscription\SubscriptionEndLastStrategy
        arguments:
            - "%thinkawitch_subscription.config.subscription.class%"
            - "%thinkawitch_subscription.config.subscription_interval.class%"
            - "@thinkawitch.subscription.strategy.product.exact"
        tags:
            - { name: thinkawitch.subscription.strategy, type: subscription, strategy: end_last_exact }